services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: "OraclePass_Str0ng!"
      ORACLE_DATABASE: XEPDB1
    ports:
      - "1522:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - dbnet

volumes:
  oracle-data:

networks:
  dbnet:
    external: true
